apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-spacegame
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: 929e4236-c41f-4452-adfd-423956b70235.cfargotunnel.com
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind:  Rule
      match: Host(`traefik3-space.k8sdevaccessito.uk`)
      services:
      - kind: Service
        name: space-game-service
        namespace: default
        port: 80
        passHostHeader: false
